component: cart
params: "REDIS_HOST:dev.elasticachae.endpoint,CATALOGUE_HOST:dev.cart.catalogue_host,CATALOGUE_PORT:dev.cart.catalogue_port"
# params: "REDIS_HOST:dev.cart.redis_host,CATALOGUE_HOST:catalogue,CATALOGUE_PORT:8080"